
exclude: [ README.md, run.sh, Gemfile, Gemfile.lock ]

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

markdown: redcarpet

redcarpet:
  extensions: ['smart']